dist: trusty
sudo: true
language: cpp
#services:
    #- docker
compiler:
    - g++

#env:
#matrix:
    #- OS=fedora DIST=24
    #- OS=ubuntu DIST=wily

#addons:
#apt:
#packages:
    #- root-system
    #- libboost  
      #- libx11-6
      #- x11-utils
      #- libx11-dev
      #- libgsl0-dev
      #- libxpm4
      #- libxft-dev
      #- libjpeg-dev
      #- libtiff4-dev
      #- libgmp3-dev
      #- libpng12-dev
      #- libxext-dev
      #- build-essential
      #- g++
before_install:
    - echo "Before installation"
    - sudo apt-get update -qq
    - sudo apt-get install -y root-system libroot-math-minuit-dev root-plugin-math-minuit2
    - sudo apt-get install -y libboost-all-dev
    #- sudo apt-get install -y libboost-system-dev \
      #libboost-serialization-dev \
      #libboost-thread-dev \
      #libboost-data-time-dev \
      #libboost-log-dev \
      #libboost-program-options-dev
install:
    - echo "Installation"
    - lsb_release
    - uname -a
    - ls /usr/include/*
    - cd ComPWA/ComPWA; ls
    - mkdir build
    - cd build
    - cmake ..
    - make -j5  

before_script:
    #- export COMPWA_DIR=$PWD
    #- export PWA_LIBS=$COMPWA_DIR/lib
    #- export QFT=/tmp/qft++
    #- export GENEVA=/tmp/geneva_1_4_0
    #- export MINUIT2=/tmp/Minuit2-5.34.14
    #- export BOOST_ROOT=/tmp/boost_1_55_0
    #- export BOOST_BUILD_PATH=$BOOST_ROOT/share/boost-build
    #- export ROOTSYS=/tmp/root_v5.34.23
    #- export CLIPS_ROOT=/tmp/clips_630
    #- export PATH=$BOOST_ROOT/bin:$ROOTSYS/bin:$PATH
    #- export LD_LIBRARY_PATH=$CLIPS_ROOT/lib:$GENEVA/lib:$ROOTSYS/lib:$MINUIT2/lib:$BOOST_ROOT/lib:$PWA_LIBS:$QFT/lib:$LD_LIBRARY_PATH 
    - export OMP_NUM_THREADS=1
#script:
    #- bjam
    #- ./run-test-apps.sh
after_success:
    - bash <(curl -s https://codecov.io/bash)

branches:
    only:
        - master
    env:
        - LANG="en_US.UTF-8"
    os:
        - linux
