# This will run on Travis' 'new' container-based infrastructure
sudo: false
language: c++

# Blacklist
branches:
    only: master
    except: gh-pages

# Environment variables
env:
    global:
        - GH_REPO_NAME: ComPWA
        - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile.travisCI
        - GH_REPO_REF: github.com/ComPWA/ComPWA.git
        - OMP_NUM_THREADS: 1
        - LANG: en_US.UTF-8
        - BASEPATH: $HOME/build/ComPWA
        - ROOTSYS: $BASEPATH/root

# Install dependencies - linux only
addons:
    apt:
        packages:
            - libboost-all-dev # Version 1.54 for trusty
            - libgsl0-dev

matrix:
  allow_failures: 
    - os: linux
      env: NAME="Build documentation"
    - os: osx

  include:
    - os: linux
      dist: trusty
      env: NAME="Build documentation"
      addons:
        apt:
          packages:
            - doxygen
            - doxygen-doc
            - doxygen-gui
            - graphviz

      script:
        # Generate and deploy documentation
        - cd $BASEPATH
        - chmod +x $TRAVIS_BUILD_DIR/doc/generateDoxygen.sh
        # Do not update doxygen for pull requests
        - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then 
          $TRAVIS_BUILD_DIR/doc/generateDoxygen.sh; 
          fi
    - os: linux
      dist: trusty  #Ubuntu14.04 LTS
      env: NAME="ROOT v6.10"
      compiler: 
        - gcc
        - clang
      before_script:
        - env
        - cd $BASEPATH
          # ROOT v6.10
        - wget https://root.cern.ch/download/root_v6.10.02.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
        - tar xpvfz root_*.tar.gz > /dev/null 2>&1
    - os: linux
      dist: trusty  #Ubuntu14.04 LTS
      compiler: gcc
      env: NAME="ROOT v6.10"
      before_script:
        - env
        - cd $BASEPATH
          # ROOT v5.34  
        - wget https://root.cern.ch/download/root_v5.34.36.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
        - tar xpvfz root_*.tar.gz > /dev/null 2>&1
    - os: osx
      osx_image: xcode8.3
      env: NAME="ROOT v6.10"
      allow_failures: true
      before_script:
        - env
        - cd $BASEPATH
        - brew install gsl boost root
        #- wget https://root.cern.ch/download/root_v6.10.02.macosx64-10.12-clang81.tar.gz
        #- tar xpvfz root_*.tar.gz > /dev/null 2>&1

# Build your code e.g. by calling make
script:
    - mkdir $BASEPATH/build
    - cd $BASEPATH/build
    - cmake ../ComPWA/
    #- make -j2 VERBOSE=1
    - make -j2 # TravisCI container-based nodes provide two CPUs
    # Job failure for testing osx
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then return 1; fi

