# This will run on Travis' 'new' container-based infrastructure
sudo: false
language: c++
os: linux
dist: trusty  #Ubuntu14.04 LTS

compiler:
      - gcc
      - clang

# Blacklist
branches:
    only:
        - master
    except:
        - gh-pages

# Environment variables
env:
    global:
        - GH_REPO_NAME: ComPWA
        - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile.travisCI
        - GH_REPO_REF: github.com/ComPWA/ComPWA.git
        - OMP_NUM_THREADS: 1
        - LANG: en_US.UTF-8
        #- ROOTSYS: $TRAVIS_BUILD_DIR/rootbuild/root
        - BASEPATH: /home/travis/build/ComPWA
        - ROOTSYS: $BASEPATH/root

# Install dependencies
addons:
    apt:
        packages:
            - libboost-all-dev
            - libgsl0-dev
            - doxygen
            - doxygen-doc
            - doxygen-gui
            - graphviz

before_script:
    - env
    - cd $BASEPATH
    - echo "Installing ROOT in path $PWD"
    - wget https://root.cern.ch/download/root_v5.34.36.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
    - tar xpvfz root_v5.34* > /dev/null 2>&1
    - mkdir $BASEPATH/build
    - cd $BASEPATH/build

# Build your code e.g. by calling make
script:
    - cmake ../ComPWA/
    - make -j2 VERBOSE=1
    - ls ../../lib
    #- make -j2 # TravisCI container-based nodes provide two CPUs

# Generate and deploy documentation
after_success:
    - cd $BASEPATH
    - chmod +x $TRAVIS_BUILD_DIR/doc/generateDoxygen.sh
      #only generate doxygen in one of two jobs
    - if [[ "$CXX" == "clang++" ]]; then $TRAVIS_BUILD_DIR/doc/generateDoxygen.sh; fi
