# This will run on Travis' 'new' container-based infrastructure
sudo: false
language: c++
os: linux
dist: trusty  #Ubuntu14.04 LTS

compiler:
      - gcc
      - clang

# Blacklist
branches:
    only:
        - master
    except:
        - gh-pages

# Environment variables
env:
    global:
        - GH_REPO_NAME: ComPWA
        - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile.travisCI
        - GH_REPO_REF: github.com/ComPWA/ComPWA.git
        - OMP_NUM_THREADS: 1
        - LANG: en_US.UTF-8
        #- ROOTSYS: $TRAVIS_BUILD_DIR/rootbuild/root
        - BASEPATH: /home/travis/build/ComPWA
        - ROOTSYS: $BASEPATH/root

# Install dependencies
addons:
    apt:
        packages:
            - libboost-all-dev
            - libgsl0-dev
            - doxygen
            - doxygen-doc
            - doxygen-gui
            - graphviz

before_script:
    - echo $TRAVIS_BUILD_DIR
    - echo $HOME
    - ls ~/*/*
    - pwd
    - env
    - cd $BASEPATH
    - echo "Installing ROOT ..."
    - wget https://root.cern.ch/download/root_v5.34.36.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
    - tar xpvfz root_v5.34* > /dev/null 2>&1

# Build your code e.g. by calling make
script:
    - cd $BASEPATH
    - mkdir build
    - cd build
    - cmake ../ComPWA/
    #- make -j2 VERBOSE=1
    - make -j2 # TravisCI container-based nodes provide two CPUs

# Generate and deploy documentation
after_success:
    - cd $TRAVIS_BUILD_DIR
    - chmod +x ./doc/generateDoxygen.sh
    - ./doc/generateDoxygen.sh
