language: cpp
compiler:
  - gcc
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y x11-common libx11-6 x11-utils libX11-dev libgsl0-dev libxpm-dev libxft-dev libjpeg-dev libtiff4-dev libgmp3-dev libpng12-dev libxext-dev; fi
  - ./install_externals.sh /tmp
before_script:
  - export export COMPWA_DIR=$PWD
  - export PWA_LIBS=$COMPWA_DIR/lib
  - export QFT=/tmp/qft++
  - export GENEVA=/tmp/geneva_1_4_0/build
  - export MINUIT2=/tmp/Minuit2-5.34.14/build
  - export BOOST_BUILD_PATH=$BOOST_ROOT/share/boost-build
  - export PATH=$BOOST_ROOT/bin:$ROOTSYS/bin:$PATH
  - export LD_LIBRARY_PATH=$GENEVA/lib:$ROOTSYS/lib/root:$MINUIT2/lib:$BOOST_ROOT/lib:$PWA_LIBS:$QFT/lib:$LD_LIBRARY_PATH 
  - export OMP_NUM_THREADS=1
script:
  - bjam
branches:
  only:
    - master
env:
  - LANG="en_US.UTF-8"
os:
  - linux
