# This will run on Travis' 'new' container-based infrastructure
sudo: false
language: c++
matrix:
  include:
    - os: linux
      dist: trusty  #Ubuntu14.04 LTS
      compiler:
        - gcc
        - clang
    - os: osx
      osx_image: xcode8.3


# Blacklist
branches:
    only:
        - master
    except:
        - gh-pages

# Environment variables
env:
    global:
        - GH_REPO_NAME: ComPWA
        - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile.travisCI
        - GH_REPO_REF: github.com/ComPWA/ComPWA.git
        - OMP_NUM_THREADS: 1
        - LANG: en_US.UTF-8
        - BASEPATH: $HOME/build/ComPWA
        - ROOTSYS: $BASEPATH/root

# Install dependencies - linux only
addons:
    apt:
        packages:
            - libboost-all-dev
            - libgsl0-dev
            - doxygen
            - doxygen-doc
            - doxygen-gui
            - graphviz

before_script:
    - env
    - cd $BASEPATH
    - echo "Installing ROOT in path $PWD"
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      brew install gsl boost;
      wget https://root.cern.ch/download/root_v6.10.02.macosx64-10.12-clang81.tar.gz;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://root.cern.ch/download/root_v6.10.02.Linux-ubuntu14-x86_64-gcc4.8.tar.gz;
      fi
    # ROOT v5.34  
    #- wget https://root.cern.ch/download/root_v5.34.36.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
    - tar xpvfz root_*.tar.gz > /dev/null 2>&1
    - mkdir $BASEPATH/build
    - cd $BASEPATH/build

# Build your code e.g. by calling make
script:
    - cmake ../ComPWA/
    #- make -j2 VERBOSE=1
    #- make -j2 # TravisCI container-based nodes provide two CPUs

# Generate and deploy documentation
after_success:
    - cd $BASEPATH
    - chmod +x $TRAVIS_BUILD_DIR/doc/generateDoxygen.sh
      #only generate doxygen in one of two jobs
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "clang++" ]]; then 
      $TRAVIS_BUILD_DIR/doc/generateDoxygen.sh; 
      fi
