# This will run on Travis' 'new' container-based infrastructure
sudo: false
language: c++

# Blacklist
branches:
    only: master
    except: gh-pages

# Environment variables
env:
    global:
        - GH_REPO_NAME: ComPWA
        - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile.travisCI
        - GH_REPO_REF: github.com/ComPWA/ComPWA.git
        - OMP_NUM_THREADS: 1
        - LANG: en_US.UTF-8
        - BASEPATH: $HOME/build/ComPWA

matrix:
  allow_failures: 
    - os: osx

  include:
    - os: linux
      dist: trusty
      env: TASK="Build documentation"
      addons: 
        apt: 
            packages:
              - doxygen
              - doxygen-doc
              - doxygen-gui
              - graphviz
      script:
        # Generate and deploy documentation
        - cd $BASEPATH
        - chmod +x $TRAVIS_BUILD_DIR/doc/generateDoxygen.sh
        # Documentation is generated and deployed to gh-pages 
        # (only if this is not a pull request).
        - $TRAVIS_BUILD_DIR/doc/generateDoxygen.sh; 

    - os: linux
      dist: trusty  #Ubuntu14.04 LTS
      env: 
        - TASK="ROOT v6.10"
        - ROOTSYS=$BASEPATH/root
      addons: 
        apt: 
            packages:
              - libboost-all-dev # Version 1.54 for trusty
              - libgsl0-dev
      compiler: 
        - clang
        - gcc
      before_script:
        - env
        - cd $BASEPATH
          # ROOT v6.10
        - wget https://root.cern.ch/download/root_v6.10.02.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
        - tar xpvfz root_*.tar.gz > /dev/null 2>&1

    - os: linux
      dist: trusty  #Ubuntu14.04 LTS
      compiler: gcc
      env: TASK="ROOT v5.34"
      addons: 
        apt: 
            packages:
              - libboost-all-dev # Version 1.54 for trusty
              - libgsl0-dev
              - root-system # ROOT v.5.34 
              - root-plugin-math-minuit2
              - libroot-math-minuit-dev
              - libroot-io-dev
              - libroot-hist-dev
              - libroot-tree-dev
      before_script:
        - env
        - echo $ROOTSYS
        - ls /usr/include/root

    - os: osx
      osx_image: xcode8.3
      env: TASK="ROOT v6.10"
      allow_failures: true
      before_script:
        - env # Debugging
          # We have to check first of a package is install, otherwise an error
          # is thrown.
        - if brew ls --versions boost > /dev/null; then echo 'Boost installed!'
          else brew install boost; fi
        - if brew ls --versions gsl > /dev/null; then echo 'GSL installed!';
          else brew install gsl; fi
        - if brew ls --versions root > /dev/null; then echo 'ROOT installed!';
          else brew install root; fi
        #- wget https://root.cern.ch/download/root_v6.10.02.macosx64-10.12-clang81.tar.gz
        #- tar xpvfz root_*.tar.gz > /dev/null 2>&1

# Build your code e.g. by calling make
script:
    - mkdir $BASEPATH/build
    - cd $BASEPATH/build
    - cmake ../ComPWA/
    - make -j2 VERBOSE=1
    #- make -j2 # TravisCI container-based nodes provide two CPUs
    # Job failure for testing osx
    - if [[ "$TRAVIS_OS_TASK" == "osx" ]]; then return 1; fi

